### ISSUE TITLE
Reimplement XmlRPC using pure C#

### ISSUE THREAD

**Issue by FrostHand** [uml-robotics/ROS.NET#10] opened 2015-05-12 22:00 UTC
C++ implementation makes using ROS.NET much harder on Mono/Unity3D platform.

**Comment by nuclearmistake** [comment] 2015-05-12 22:18
Aye... Tis a bit dirty... But is it as significant an impediment to mono as the shenanigans being done for message generation? Or have you worked around that?

**Comment by FrostHand** [comment] 2015-05-12 23:13
Seems like I've missed the real problem: I thought that native (C++) was causing dll import errors. Actually, that problems were caused by MathNet. Neither .net 4.0, nor 3.5 version can be imported. So Im going to just reimplement tf_node.cs stuff using vectors, provided by Unity (they are not so good, but just more than enough for TF calculations). It is a good reason to make separate project for TF client, by the way.

Static message generation (do you mean generated 'Messages' project?) is mostly OK for C# projects. At least it is not the blocker for me right now.

**Comment by nuclearmistake** [comment] 2015-05-12 23:27
Ah yes... The TF should in hindsight probably live elsewhere. There was a
point fairly recently where the TF stuff was implemented with a C#
translation of bullet types... But it had always seemed "slightly left"
(not quite right), so I've historically used adapter nodes to hide TF from
my windows nodes.

I'm not attached to either, and they shouldn't be dependencies of other
core components... If you're not using TF in your project, you can probably
just remove them to expedite your bringup

**Comment by nuclearmistake** [comment] 2015-05-14 18:39
https://github.com/uml-robotics/ROS.NET/compare/NewTF has a reorged TF that might have a bit of a correctness regression, but definitely does not depend on mathnet spatial. I'll write up some tests for it and double check the various types' operator overloads at some point in the next week or two.

**Comment by FrostHand** [comment] 2015-05-25 22:09
Hmm. Made my own TF client using Unity3D vector math. Now I have returned to problems with loading native  XmlRpcWin32.dll to unity. Some sort of x64->x32 compatibility problems, causing ether "failed to load DLL" or heavy crash.

**Comment by FrostHand** [comment] 2015-05-26 07:38
I began porting XmpRpcWin32 to pure C#. It will take me a week or two

**Comment by FrostHand** [comment] 2015-05-31 18:53
Half work is done. It is certainly 'sharper' now. Most notable changes:
- There is no need to warp between IntPtr and actual object, so no reasons for SegFault and many more errors related to unmanaged code. 
- XML serialization is replaced by .NET framework implementations.

Need another week to test and fix the rest

**Comment by nickkazepis** [comment] 2015-06-02 09:19
Hello!
I don't know whether this might be helpful (probably it won't be) but there is this relevant library http://xml-rpc.net/ that could potentially help you. (More like a question than a statement :)
Anyway, good luck! I've recently dove into ROS and I'm quite excited with the "ecosystem". I hope that in the future I will have more time to actively engage in this C# project! :)

**Comment by FrostHand** [comment] 2015-06-03 06:59
I've decided to use XmlRpc_Wrapper API, and just to reimplement all its contents using C#. Still I had to change some code in core ROS project.

ROS master registration works fine now, but there are problems with getting subscribed (chatterer test). And I am sure that there are more problems.

**Comment by nuclearmistake** [comment] 2015-06-03 14:40
I derived those structs by turning up the debug values in xmlrpc_util.cc...
You ought to be able to do the same to see what the values being sent and
received should be... But getting the xmlrpcvalue to behave like a union
that could be a dictionary of values, array of values, or one of various
primitive types might be where you're having issues with topic negotiation.

Does subscription work? Having a subscriber connect to an advertised topic
requires properly handling an inbound function call after successfully
calling a function on master, whiles subscribing just requires two remote
function calls.

**Comment by FrostHand** [comment] 2015-06-03 14:49
I hope I'll investigate it further today, or continue at the weekends. 
I've already reimplemented XmlRpcValue, that was the first thing I've dealth with. Now I can certainly say that rosmaster registration was OK, rostopic list/rosnode list has printed proper info about my C# node and advertised. I guess I've broken dispatcher class (the one that calls 'select' for a group of sockets), so it does not accept incoming connections properly.

**Comment by nuclearmistake** [comment] 2015-06-03 14:55
If sub's work but pubs don't, then that would be my diagnosis as well. Great work so far!

**Comment by FrostHand** [comment] 2015-06-09 06:49
The first problem was simple: I've just forgot to (re)implement XmlRpcServer. The second one is harder: SimplePublisher still cannot publish anything properly. I've tried to listen to it by 'rostopic echo /chatter'. I will attach here XmlRpc request/response log tomorrow.

**Comment by nuclearmistake** [comment] 2015-06-23 19:58
Frost, looks like publishing is partially broken because XmlRpcServer isn't implemented.

Subscription.cs @ line 248 shows the subscriber-side of the xmlrpc communications necessary for a subscriber to connect to a publisher, and it definitely involves responding to an XmlRpc function call

**Comment by FrostHand** [comment] 2015-06-23 20:30
I have already reimplemented most of XMLRPC server infrastructure. Now it properly parses requests and tries to send reasonable responses. But it seems that responses are wrong somewhere. I should run another heavy multi application step-by-step debug session with both publisher and subscriber to figure it out.

I will look at it when I get enough time again. This month is very busy. But on the other hand I should make some hacks to ros_comm package (roslaunch), so I will definitely get more knowledge about XMLRPC.

**Comment by FrostHand** [comment] 2015-07-05 10:30
At last, publishing works. I can run simple .NET publisher and get reasonable output using rostopic echo /chatter
Now I should fix .NET subscribing, check and clean up some stuff. And then I create pull request

**Comment by nuclearmistake** [comment] 2016-02-26 00:47
100% merged into master and working.

Thanks for the commits, man.
I was delaying merging to find an issue with very large HTTP connection headers, and finally got time to look for the issue and fix it. B-)

**Closed by nuclearmistake** 2016-02-26 00:47 UTC
